apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 965240197246.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 965240197246.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: b76c17d3
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
